name: Release and publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          new_version: ${{ github.ref }}
      - run: |
          sed -ie 's|\(.*"version"\): "\(.*\)",.*|\1: '"\"$new_version\",|" package.json
          yarn install
          git add package.json
          git commit -m "Release ${{ github.ref }}"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
