name: Release and publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          sed -ie 's|\(.*"version"\): "\(.*\)",.*|\1: '"\"$(echo "${{ github.ref }}" | sed 's/refs\/tags\/*//g')\",|" package.json
          yarn install
          git config --local user.email "ask@van.dermeer.de"
          git config --local user.name "Thomas Scharke"
          git add package.json
          git tag $(echo "${{ github.ref }}" | sed 's/refs\/tags\/*//g') -f
          git commit -m "Release $(echo "${{ github.ref }}" | sed 's/refs\/tags\/*//g')"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
